/**
         | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | A | B | C | D | E | F

| U+250x | ─ | ━ | │ | ┃ | ┄ | ┅ | ┆ | ┇ | ┈ | ┉ | ┊ | ┋ | ┌ | ┍ | ┎ | ┏

| U+251x | ┐ | ┑ | ┒ | ┓ | └ | ┕ | ┖ | ┗ | ┘ | ┙ | ┚ | ┛ | ├ | ┝ | ┞ | ┟

| U+252x | ┠ | ┡ | ┢ | ┣ | ┤ | ┥ | ┦ | ┧ | ┨ | ┩ | ┪ | ┫ | ┬ | ┭ | ┮ | ┯

| U+253x | ┰ | ┱ | ┲ | ┳ | ┴ | ┵ | ┶ | ┷ | ┸ | ┹ | ┺ | ┻ | ┼ | ┽ | ┾ | ┿

| U+254x | ╀ | ╁ | ╂ | ╃ | ╄ | ╅ | ╆ | ╇ | ╈ | ╉ | ╊ | ╋ | ╌ | ╍ | ╎ | ╏

| U+255x | ═ | ║ | ╒ | ╓ | ╔ | ╕ | ╖ | ╗ | ╘ | ╙ | ╚ | ╛ | ╜ | ╝ | ╞ | ╟

| U+256x | ╠ | ╡ | ╢ | ╣ | ╤ | ╥ | ╦ | ╧ | ╨ | ╩ | ╪ | ╫ | ╬ | ╭ | ╮ | ╯

| U+257x | ╰ | ╱ | ╲ | ╳ | ╴ | ╵ | ╶ | ╷ | ╸ | ╹ | ╺ | ╻ | ╼ | ╽ | ╾ | ╿

*/


// Light and heavy solid lines
#define BOX_DRAWINGS_LIGHT_HORIZONTAL 0x2500    // ─ BOX DRAWINGS LIGHT HORIZONTAL
#define BOX_DRAWINGS_HEAVY_HORIZONTAL 0x2501    // ━ BOX DRAWINGS HEAVY HORIZONTAL
#define BOX_DRAWINGS_LIGHT_VERTICAL 0x2502      // │ BOX DRAWINGS LIGHT VERTICAL
#define BOX_DRAWINGS_HEAVY_VERTICAL 0x2503      // ┃ BOX DRAWINGS HEAVY VERTICAL

// Light and heavy line box components
#define BOX_DRAWINGS_LIGHT_DOWN_AND_RIGHT 0x250C    // ┌ BOX DRAWINGS LIGHT DOWN AND RIGHT
#define BOX_DRAWINGS_DOWN_LIGHT_AND_RIGHT_HEAVY 0x250D  // ┍ BOX DRAWINGS DOWN LIGHT AND RIGHT HEAVY
#define BOX_DRAWINGS_DOWN_HEAVY_AND_RIGHT_LIGHT 0x250E  // ┎ BOX DRAWINGS DOWN HEAVY AND RIGHT LIGHT
#define BOX_DRAWINGS_HEAVY_DOWN_AND_RIGHT 0x250F    // ┏ BOX DRAWINGS HEAVY DOWN AND RIGHT
#define BOX_DRAWINGS_LIGHT_DOWN_AND_LEFT 0x2510     // ┐ BOX DRAWINGS LIGHT DOWN AND LEFT
#define BOX_DRAWINGS_DOWN_LIGHT_AND_LEFT_HEAVY 0x2511   // ┑ BOX DRAWINGS DOWN LIGHT AND LEFT HEAVY
#define BOX_DRAWINGS_DOWN_HEAVY_AND_LEFT_LIGHT 0x2512   // ┒ BOX DRAWINGS DOWN HEAVY AND LEFT LIGHT
#define BOX_DRAWINGS_HEAVY_DOWN_AND_LEFT 0x2513     // ┓ BOX DRAWINGS HEAVY DOWN AND LEFT
#define BOX_DRAWINGS_LIGHT_UP_AND_RIGHT 0x2514  // └ BOX DRAWINGS LIGHT UP AND RIGHT
#define BOX_DRAWINGS_UP_LIGHT_AND_RIGHT_HEAVY 0x2515    // ┕ BOX DRAWINGS UP LIGHT AND RIGHT HEAVY
#define BOX_DRAWINGS_UP_HEAVY_AND_RIGHT_LIGHT 0x2516    // ┖ BOX DRAWINGS UP HEAVY AND RIGHT LIGHT
#define BOX_DRAWINGS_HEAVY_UP_AND_RIGHT 0x2517  // ┗ BOX DRAWINGS HEAVY UP AND RIGHT
#define BOX_DRAWINGS_LIGHT_UP_AND_LEFT 0x2518   // ┘ BOX DRAWINGS LIGHT UP AND LEFT
#define BOX_DRAWINGS_UP_LIGHT_AND_LEFT_HEAVY 0x2519     // ┙ BOX DRAWINGS UP LIGHT AND LEFT HEAVY
#define BOX_DRAWINGS_UP_HEAVY_AND_LEFT_LIGHT 0x251A     // ┚ BOX DRAWINGS UP HEAVY AND LEFT LIGHT
#define BOX_DRAWINGS_HEAVY_UP_AND_LEFT 0x251B           // ┛ BOX DRAWINGS HEAVY UP AND LEFT
#define BOX_DRAWINGS_LIGHT_VERTICAL_AND_RIGHT 0x251C    // ├ BOX DRAWINGS LIGHT VERTICAL AND RIGHT
#define BOX_DRAWINGS_VERTICAL_LIGHT_AND_RIGHT_HEAVY 0x251D  // ┝ BOX DRAWINGS VERTICAL LIGHT AND RIGHT HEAVY
#define BOX_DRAWINGS_UP_HEAVY_AND_RIGHT_DOWN_LIGHT 0x251E   // ┞ BOX DRAWINGS UP HEAVY AND RIGHT DOWN LIGHT
#define BOX_DRAWINGS_DOWN_HEAVY_AND_RIGHT_UP_LIGHT 0x251F   // ┟ BOX DRAWINGS DOWN HEAVY AND RIGHT UP LIGHT
#define BOX_DRAWINGS_VERTICAL_HEAVY_AND_RIGHT_LIGHT 0x2520  // ┠ BOX DRAWINGS VERTICAL HEAVY AND RIGHT LIGHT
#define BOX_DRAWINGS_DOWN_LIGHT_AND_RIGHT_UP_HEAVY 0x2521   // ┡ BOX DRAWINGS DOWN LIGHT AND RIGHT UP HEAVY
#define BOX_DRAWINGS_UP_LIGHT_AND_RIGHT_DOWN_HEAVY 0x2522   // ┢ BOX DRAWINGS UP LIGHT AND RIGHT DOWN HEAVY
#define BOX_DRAWINGS_HEAVY_VERTICAL_AND_RIGHT 0x2523    // ┣ BOX DRAWINGS HEAVY VERTICAL AND RIGHT
#define BOX_DRAWINGS_LIGHT_VERTICAL_AND_LEFT 0x2524     // ┤ BOX DRAWINGS LIGHT VERTICAL AND LEFT
#define BOX_DRAWINGS_VERTICAL_LIGHT_AND_LEFT_HEAVY 0x2525   // ┥ BOX DRAWINGS VERTICAL LIGHT AND LEFT HEAVY
#define BOX_DRAWINGS_UP_HEAVY_AND_LEFT_DOWN_LIGHT 0x2526    // ┦ BOX DRAWINGS UP HEAVY AND LEFT DOWN LIGHT
#define BOX_DRAWINGS_DOWN_HEAVY_AND_LEFT_UP_LIGHT 0x2527    // ┧ BOX DRAWINGS DOWN HEAVY AND LEFT UP LIGHT
#define BOX_DRAWINGS_VERTICAL_HEAVY_AND_LEFT_LIGHT 0x2528   // ┨ BOX DRAWINGS VERTICAL HEAVY AND LEFT LIGHT
#define BOX_DRAWINGS_DOWN_LIGHT_AND_LEFT_UP_HEAVY 0x2529    // ┩ BOX DRAWINGS DOWN LIGHT AND LEFT UP HEAVY
#define BOX_DRAWINGS_UP_LIGHT_AND_LEFT_DOWN_HEAVY 0x252A    // ┪ BOX DRAWINGS UP LIGHT AND LEFT DOWN HEAVY
#define BOX_DRAWINGS_HEAVY_VERTICAL_AND_LEFT 0x252B         // ┫ BOX DRAWINGS HEAVY VERTICAL AND LEFT
#define BOX_DRAWINGS_LIGHT_DOWN_AND_HORIZONTAL 0x252C   // ┬ BOX DRAWINGS LIGHT DOWN AND HORIZONTAL
#define BOX_DRAWINGS_LEFT_HEAVY_AND_RIGHT_DOWN_LIGHT 0x252D     // ┭ BOX DRAWINGS LEFT HEAVY AND RIGHT DOWN LIGHT
#define BOX_DRAWINGS_RIGHT_HEAVY_AND_LEFT_DOWN_LIGHT 0x252E     // ┮ BOX DRAWINGS RIGHT HEAVY AND LEFT DOWN LIGHT
#define BOX_DRAWINGS_DOWN_LIGHT_AND_HORIZONTAL_HEAVY 0x252F     // ┯ BOX DRAWINGS DOWN LIGHT AND HORIZONTAL HEAVY
#define BOX_DRAWINGS_DOWN_HEAVY_AND_HORIZONTAL_LIGHT 0x2530     // ┰ BOX DRAWINGS DOWN HEAVY AND HORIZONTAL LIGHT
#define BOX_DRAWINGS_RIGHT_LIGHT_AND_LEFT_DOWN_HEAVY 0x2531     // ┱ BOX DRAWINGS RIGHT LIGHT AND LEFT DOWN HEAVY
#define BOX_DRAWINGS_LEFT_LIGHT_AND_RIGHT_DOWN_HEAVY 0x2532     // ┲ BOX DRAWINGS LEFT LIGHT AND RIGHT DOWN HEAVY
#define BOX_DRAWINGS_HEAVY_DOWN_AND_HORIZONTAL 0x2533   // ┳ BOX DRAWINGS HEAVY DOWN AND HORIZONTAL
#define BOX_DRAWINGS_LIGHT_UP_AND_HORIZONTAL 0x2534     // ┴ BOX DRAWINGS LIGHT UP AND HORIZONTAL
#define BOX_DRAWINGS_LEFT_HEAVY_AND_RIGHT_UP_LIGHT 0x2535   // ┵ BOX DRAWINGS LEFT HEAVY AND RIGHT UP LIGHT
#define BOX_DRAWINGS_RIGHT_HEAVY_AND_LEFT_UP_LIGHT 0x2536   // ┶ BOX DRAWINGS RIGHT HEAVY AND LEFT UP LIGHT
#define BOX_DRAWINGS_UP_LIGHT_AND_HORIZONTAL_HEAVY 0x2537   // ┷ BOX DRAWINGS UP LIGHT AND HORIZONTAL HEAVY
#define BOX_DRAWINGS_UP_HEAVY_AND_HORIZONTAL_LIGHT 0x2538   // ┸ BOX DRAWINGS UP HEAVY AND HORIZONTAL LIGHT
#define BOX_DRAWINGS_RIGHT_LIGHT_AND_LEFT_UP_HEAVY 0x2539   // ┹ BOX DRAWINGS RIGHT LIGHT AND LEFT UP HEAVY
#define BOX_DRAWINGS_LEFT_LIGHT_AND_RIGHT_UP_HEAVY 0x253A   // ┺ BOX DRAWINGS LEFT LIGHT AND RIGHT UP HEAVY
#define BOX_DRAWINGS_HEAVY_UP_AND_HORIZONTAL 0x253B         // ┻ BOX DRAWINGS HEAVY UP AND HORIZONTAL
#define BOX_DRAWINGS_LIGHT_VERTICAL_AND_HORIZONTAL 0x253C   // ┼ BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL
#define BOX_DRAWINGS_LEFT_HEAVY_AND_RIGHT_VERTICAL_LIGHT 0x253D     // ┽ BOX DRAWINGS LEFT HEAVY AND RIGHT VERTICAL LIGHT
#define BOX_DRAWINGS_RIGHT_HEAVY_AND_LEFT_VERTICAL_LIGHT 0x253E     // ┾ BOX DRAWINGS RIGHT HEAVY AND LEFT VERTICAL LIGHT
#define BOX_DRAWINGS_VERTICAL_LIGHT_AND_HORIZONTAL_HEAVY 0x253F     // ┿ BOX DRAWINGS VERTICAL LIGHT AND HORIZONTAL HEAVY
#define BOX_DRAWINGS_UP_HEAVY_AND_DOWN_HORIZONTAL_LIGHT 0x2540  // ╀ BOX DRAWINGS UP HEAVY AND DOWN HORIZONTAL LIGHT
#define BOX_DRAWINGS_DOWN_HEAVY_AND_UP_HORIZONTAL_LIGHT 0x2541  // ╁ BOX DRAWINGS DOWN HEAVY AND UP HORIZONTAL LIGHT
#define BOX_DRAWINGS_VERTICAL_HEAVY_AND_HORIZONTAL_LIGHT 0x2542     // ╂ BOX DRAWINGS VERTICAL HEAVY AND HORIZONTAL LIGHT
#define BOX_DRAWINGS_LEFT_UP_HEAVY_AND_RIGHT_DOWN_LIGHT 0x2543  // ╃ BOX DRAWINGS LEFT UP HEAVY AND RIGHT DOWN LIGHT
#define BOX_DRAWINGS_RIGHT_UP_HEAVY_AND_LEFT_DOWN_LIGHT 0x2544  // ╄ BOX DRAWINGS RIGHT UP HEAVY AND LEFT DOWN LIGHT
#define BOX_DRAWINGS_LEFT_DOWN_HEAVY_AND_RIGHT_UP_LIGHT 0x2545  // ╅ BOX DRAWINGS LEFT DOWN HEAVY AND RIGHT UP LIGHT
#define BOX_DRAWINGS_RIGHT_DOWN_HEAVY_AND_LEFT_UP_LIGHT 0x2546  // ╆ BOX DRAWINGS RIGHT DOWN HEAVY AND LEFT UP LIGHT
#define BOX_DRAWINGS_DOWN_LIGHT_AND_UP_HORIZONTAL_HEAVY 0x2547  // ╇ BOX DRAWINGS DOWN LIGHT AND UP HORIZONTAL HEAVY
#define BOX_DRAWINGS_UP_LIGHT_AND_DOWN_HORIZONTAL_HEAVY 0x2548  // ╈ BOX DRAWINGS UP LIGHT AND DOWN HORIZONTAL HEAVY
#define BOX_DRAWINGS_RIGHT_LIGHT_AND_LEFT_VERTICAL_HEAVY 0x2549     // ╉ BOX DRAWINGS RIGHT LIGHT AND LEFT VERTICAL HEAVY
#define BOX_DRAWINGS_LEFT_LIGHT_AND_RIGHT_VERTICAL_HEAVY 0x254A     // ╊ BOX DRAWINGS LEFT LIGHT AND RIGHT VERTICAL HEAVY
#define BOX_DRAWINGS_HEAVY_VERTICAL_AND_HORIZONTAL 0x254B   // ╋ BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL

// Double lines
#define BOX_DRAWINGS_DOUBLE_HORIZONTAL 0x2550   // ═ BOX DRAWINGS DOUBLE HORIZONTAL
#define BOX_DRAWINGS_DOUBLE_VERTICAL 0x2551     // ║ BOX DRAWINGS DOUBLE VERTICAL

// Light and double line box components
#define BOX_DRAWINGS_DOWN_SINGLE_AND_RIGHT_DOUBLE 0x2552    // ╒ BOX DRAWINGS DOWN SINGLE AND RIGHT DOUBLE
#define BOX_DRAWINGS_DOWN_DOUBLE_AND_RIGHT_SINGLE 0x2553    // ╓ BOX DRAWINGS DOWN DOUBLE AND RIGHT SINGLE
#define BOX_DRAWINGS_DOUBLE_DOWN_AND_RIGHT 0x2554   // ╔ BOX DRAWINGS DOUBLE DOWN AND RIGHT
#define BOX_DRAWINGS_DOWN_SINGLE_AND_LEFT_DOUBLE 0x2555     // ╕ BOX DRAWINGS DOWN SINGLE AND LEFT DOUBLE
#define BOX_DRAWINGS_DOWN_DOUBLE_AND_LEFT_SINGLE 0x2556     // ╖ BOX DRAWINGS DOWN DOUBLE AND LEFT SINGLE
#define BOX_DRAWINGS_DOUBLE_DOWN_AND_LEFT 0x2557    // ╗ BOX DRAWINGS DOUBLE DOWN AND LEFT
#define BOX_DRAWINGS_UP_SINGLE_AND_RIGHT_DOUBLE 0x2558  // ╘ BOX DRAWINGS UP SINGLE AND RIGHT DOUBLE
#define BOX_DRAWINGS_UP_DOUBLE_AND_RIGHT_SINGLE 0x2559  // ╙ BOX DRAWINGS UP DOUBLE AND RIGHT SINGLE
#define BOX_DRAWINGS_DOUBLE_UP_AND_RIGHT 0x255A     // ╚ BOX DRAWINGS DOUBLE UP AND RIGHT
#define BOX_DRAWINGS_UP_SINGLE_AND_LEFT_DOUBLE 0x255B   // ╛ BOX DRAWINGS UP SINGLE AND LEFT DOUBLE
#define BOX_DRAWINGS_UP_DOUBLE_AND_LEFT_SINGLE 0x255C   // ╜ BOX DRAWINGS UP DOUBLE AND LEFT SINGLE
#define BOX_DRAWINGS_DOUBLE_UP_AND_LEFT 0x255D  // ╝ BOX DRAWINGS DOUBLE UP AND LEFT
#define BOX_DRAWINGS_VERTICAL_SINGLE_AND_RIGHT_DOUBLE 0x255E    // ╞ BOX DRAWINGS VERTICAL SINGLE AND RIGHT DOUBLE
#define BOX_DRAWINGS_VERTICAL_DOUBLE_AND_RIGHT_SINGLE 0x255F    // ╟ BOX DRAWINGS VERTICAL DOUBLE AND RIGHT SINGLE
#define BOX_DRAWINGS_DOUBLE_VERTICAL_AND_RIGHT 0x2560   // ╠ BOX DRAWINGS DOUBLE VERTICAL AND RIGHT
#define BOX_DRAWINGS_VERTICAL_SINGLE_AND_LEFT_DOUBLE 0x2561     // ╡ BOX DRAWINGS VERTICAL SINGLE AND LEFT DOUBLE
#define BOX_DRAWINGS_VERTICAL_DOUBLE_AND_LEFT_SINGLE 0x2562     // ╢ BOX DRAWINGS VERTICAL DOUBLE AND LEFT SINGLE
#define BOX_DRAWINGS_DOUBLE_VERTICAL_AND_LEFT 0x2563    // ╣ BOX DRAWINGS DOUBLE VERTICAL AND LEFT
#define BOX_DRAWINGS_DOWN_SINGLE_AND_HORIZONTAL_DOUBLE 0x2564   // ╤ BOX DRAWINGS DOWN SINGLE AND HORIZONTAL DOUBLE
#define BOX_DRAWINGS_DOWN_DOUBLE_AND_HORIZONTAL_SINGLE 0x2565   // ╥ BOX DRAWINGS DOWN DOUBLE AND HORIZONTAL SINGLE
#define BOX_DRAWINGS_DOUBLE_DOWN_AND_HORIZONTAL 0x2566  // ╦ BOX DRAWINGS DOUBLE DOWN AND HORIZONTAL
#define BOX_DRAWINGS_UP_SINGLE_AND_HORIZONTAL_DOUBLE 0x2567     // ╧ BOX DRAWINGS UP SINGLE AND HORIZONTAL DOUBLE
#define BOX_DRAWINGS_UP_DOUBLE_AND_HORIZONTAL_SINGLE 0x2568     // ╨ BOX DRAWINGS UP DOUBLE AND HORIZONTAL SINGLE
#define BOX_DRAWINGS_DOUBLE_UP_AND_HORIZONTAL 0x2569    // ╩ BOX DRAWINGS DOUBLE UP AND HORIZONTAL
#define BOX_DRAWINGS_VERTICAL_SINGLE_AND_HORIZONTAL_DOUBLE 0x256A   // ╪ BOX DRAWINGS VERTICAL SINGLE AND HORIZONTAL DOUBLE
#define BOX_DRAWINGS_VERTICAL_DOUBLE_AND_HORIZONTAL_SINGLE 0x256B   //╫ BOX DRAWINGS VERTICAL DOUBLE AND HORIZONTAL SINGLE
#define BOX_DRAWINGS_DOUBLE_VERTICAL_AND_HORIZONTAL 0x256C  // ╬ BOX DRAWINGS DOUBLE VERTICAL AND HORIZONTAL

// Character cell arcs
#define BOX_DRAWINGS_LIGHT_ARC_DOWN_AND_RIGHT 0x256D    // ╭ BOX DRAWINGS LIGHT ARC DOWN AND RIGHT
#define BOX_DRAWINGS_LIGHT_ARC_DOWN_AND_LEFT 0x256E     // ╮ BOX DRAWINGS LIGHT ARC DOWN AND LEFT
#define BOX_DRAWINGS_LIGHT_ARC_UP_AND_LEFT 0x256F   // ╯ BOX DRAWINGS LIGHT ARC UP AND LEFT
#define BOX_DRAWINGS_LIGHT_ARC_UP_AND_RIGHT 0x2570  // ╰ BOX DRAWINGS LIGHT ARC UP AND RIGHT

// Light and heavy dashed lines
#define BOX_DRAWINGS_LIGHT_TRIPLE_DASH_HORIZONTAL 0x2504    // ┄ BOX DRAWINGS LIGHT TRIPLE DASH HORIZONTAL
#define BOX_DRAWINGS_HEAVY_TRIPLE_DASH_HORIZONTAL 0x2505    // ┅ BOX DRAWINGS HEAVY TRIPLE DASH HORIZONTAL
#define BOX_DRAWINGS_LIGHT_TRIPLE_DASH_VERTICAL 0x2506  // ┆ BOX DRAWINGS LIGHT TRIPLE DASH VERTICAL
#define BOX_DRAWINGS_HEAVY_TRIPLE_DASH_VERTICAL 0x2507  // ┇ BOX DRAWINGS HEAVY TRIPLE DASH VERTICAL
#define BOX_DRAWINGS_LIGHT_QUADRUPLE_DASH_HORIZONTAL 0x2508     // ┈ BOX DRAWINGS LIGHT QUADRUPLE DASH HORIZONTAL
#define BOX_DRAWINGS_HEAVY_QUADRUPLE_DASH_HORIZONTAL 0x2509     // ┉ BOX DRAWINGS HEAVY QUADRUPLE DASH HORIZONTAL
#define BOX_DRAWINGS_LIGHT_QUADRUPLE_DASH_VERTICAL 0x250A   // ┊ BOX DRAWINGS LIGHT QUADRUPLE DASH VERTICAL
#define BOX_DRAWINGS_HEAVY_QUADRUPLE_DASH_VERTICAL 0x250B   // ┋ BOX DRAWINGS HEAVY QUADRUPLE DASH VERTICAL

// Light and heavy dashed lines
#define BOX_DRAWINGS_LIGHT_DOUBLE_DASH_HORIZONTAL 0x254C    // ╌ BOX DRAWINGS LIGHT DOUBLE DASH HORIZONTAL
#define BOX_DRAWINGS_HEAVY_DOUBLE_DASH_HORIZONTAL 0x254D    // ╍ BOX DRAWINGS HEAVY DOUBLE DASH HORIZONTAL
#define BOX_DRAWINGS_LIGHT_DOUBLE_DASH_VERTICAL 0x254E  // ╎ BOX DRAWINGS LIGHT DOUBLE DASH VERTICAL
#define BOX_DRAWINGS_HEAVY_DOUBLE_DASH_VERTICAL 0x254F  // ╏ BOX DRAWINGS HEAVY DOUBLE DASH VERTICAL

// Character cell diagonals
// Legacy Computing block.
#define BOX_DRAWINGS_LIGHT_DIAGONAL_UPPER_RIGHT_TO_LOWER_LEFT 0x2571    // ╱ BOX DRAWINGS LIGHT DIAGONAL UPPER RIGHT TO LOWER LEFT
#define BOX_DRAWINGS_LIGHT_DIAGONAL_UPPER_LEFT_TO_LOWER_RIGHT 0x2572    // ╲ BOX DRAWINGS LIGHT DIAGONAL UPPER LEFT TO LOWER RIGHT
#define BOX_DRAWINGS_LIGHT_DIAGONAL_CROSS 0x2573    // ╳ BOX DRAWINGS LIGHT DIAGONAL CROSS

// Light and heavy half lines
#define BOX_DRAWINGS_LIGHT_LEFT 0x2574  // ╴ BOX DRAWINGS LIGHT LEFT
#define BOX_DRAWINGS_LIGHT_UP 0x2575    // ╵ BOX DRAWINGS LIGHT UP
#define BOX_DRAWINGS_LIGHT_RIGHT 0x2576     // ╶ BOX DRAWINGS LIGHT RIGHT
#define BOX_DRAWINGS_LIGHT_DOWN 0x2577  // ╷ BOX DRAWINGS LIGHT DOWN
#define BOX_DRAWINGS_HEAVY_LEFT 0x2578  // ╸ BOX DRAWINGS HEAVY LEFT
#define BOX_DRAWINGS_HEAVY_UP 0x2579    // ╹ BOX DRAWINGS HEAVY UP
#define BOX_DRAWINGS_HEAVY_RIGHT 0x257A     // ╺ BOX DRAWINGS HEAVY RIGHT
#define BOX_DRAWINGS_HEAVY_DOWN 0x257B  //╻ BOX DRAWINGS HEAVY DOWN

// Mixed light and heavy lines
#define BOX_DRAWINGS_LIGHT_LEFT_AND_HEAVY_RIGHT 0x257C  // ╼ BOX DRAWINGS LIGHT LEFT AND HEAVY RIGHT
#define BOX_DRAWINGS_LIGHT_UP_AND_HEAVY_DOWN 0x257D     // ╽ BOX DRAWINGS LIGHT UP AND HEAVY DOWN
#define BOX_DRAWINGS_HEAVY_LEFT_AND_LIGHT_RIGHT 0x257E  // ╾ BOX DRAWINGS HEAVY LEFT AND LIGHT RIGHT
#define BOX_DRAWINGS_HEAVY_UP_AND_LIGHT_DOWN 0x257F     // ╿ BOX DRAWINGS HEAVY UP AND LIGHT DOWN

